version: '3.9'

services:
  postgres:
    image: postgres:14
    restart: always
    healthcheck:
      test: ['CMD', 'pg_health', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: codetalent
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - postgres
    environment:
      - SERVER_PORT=3001
      - DATABASE_NAME=codetalent
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
    ports:
      - '3001:3001'

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db

volumes:
  postgres-data:
  mongodb-data:
